<h1 align='center' style='color:green'>Finding best model and hyper parameter tunning using GridSearchCV</h1>

## Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

import warnings
warnings.filterwarnings("ignore")

In [2]:
dataset = pd.read_csv('Breast_Cancer_Diagnostic.csv')
dataset.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean diagnosis  
0                 0.07871         M  
1                 0.05667         M  
2                 0.05999         M  
3                 0.09744         M  
4                 0.05883         M

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   radius_mean             569 non-null    float64
 1   texture_mean            569 non-null    float64
 2   perimeter_mean          569 non-null    float64
 3   area_mean               569 non-null    float64
 4   smoothness_mean         569 non-null    float64
 5   compactness_mean        569 non-null    float64
 6   concavity_mean          569 non-null    float64
 7   concave points_mean     569 non-null    float64
 8   symmetry_mean           569 non-null    float64
 9   fractal_dimension_mean  569 non-null    float64
 10  diagnosis               569 non-null    object 
dtypes: float64(10), object(1)
memory usage: 49.0+ KB


In [4]:
dataset.shape

(569, 11)

In [5]:
dataset.columns

Index(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'diagnosis'],
      dtype='object')

In [6]:
target = dataset['diagnosis']
target.head(23)

0     M
1     M
2     M
3     M
4     M
5     M
6     M
7     M
8     M
9     M
10    M
11    M
12    M
13    M
14    M
15    M
16    M
17    M
18    M
19    B
20    B
21    B
22    M
Name: diagnosis, dtype: object

In [7]:
features = dataset.drop('diagnosis', axis=1)
features.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  
0                 0.07871  
1                 0.05667  
2                 0.05999  
3                 0.09744  
4                 0.05883

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3)

In [9]:
X_train.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
207       17.010         20.26          109.70      904.3          0.08772   
494       13.160         20.54           84.06      538.7          0.07335   
488       11.680         16.17           75.49      420.5          0.11280   
515       11.340         18.61           72.76      391.2          0.10490   
61         8.598         20.98           54.66      221.8          0.12430   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
207           0.07304         0.06950             0.053900         0.2026   
494           0.05275         0.01800             0.012560         0.1713   
488           0.09263         0.04279             0.031320         0.1853   
515           0.08499         0.04302             0.025940         0.1927   
61            0.08963         0.03000             0.009259         0.1828   

     fractal_dimension_mean  
207                 0.05223  
494                 0.05888  
488                 0.06401  
515                 0.06211  
61                  0.06757

In [10]:
X_test.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
473       12.270         29.97           77.42      465.4          0.07699   
205       15.120         16.68           98.78      716.6          0.08876   
239       17.460         39.28          113.40      920.6          0.09812   
412        9.397         21.68           59.75      268.8          0.07969   
527       12.340         12.27           78.94      468.5          0.09003   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
473           0.03398         0.00000             0.000000         0.1701   
205           0.09588         0.07550             0.040790         0.1594   
239           0.12980         0.14170             0.088110         0.1809   
412           0.06053         0.03735             0.005128         0.1274   
527           0.06307         0.02958             0.026470         0.1689   

     fractal_dimension_mean  
473                 0.05960  
205                 0.05986  
239                 0.05966  
412                 0.06724  
527                 0.05808

In [11]:
from sklearn.svm import SVC

In [12]:
model = SVC(kernel='rbf', C=1, gamma='auto')
model.fit(X_train,y_train)

model.score(X_test, y_test)

0.6783625730994152

<h2 style='color:orange'>Use K Fold Cross validation</h2>

**Manually try suppling models with different parameters to cross_val_score function with 5 fold cross validation**

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
sv1=cross_val_score(SVC(kernel='rbf',C=1,gamma='auto'),features, target, cv=5)
sv1

array([0.71052632, 0.71929825, 0.74561404, 0.72807018, 0.68141593])

In [15]:
sv1.mean()

0.7169849402266728

In [16]:
sv2=cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),features, target, cv=5)
sv2

array([0.70175439, 0.71929825, 0.75438596, 0.71052632, 0.71681416])

In [17]:
sv2.mean()

0.7205558143145475

In [18]:
sv3=cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),features, target, cv=5)
sv3

array([0.70175439, 0.71929825, 0.75438596, 0.71052632, 0.71681416])

In [19]:
sv3.mean()  

0.7205558143145475

<h2 style='color:blue'>Use GridSearchCV</h2>

**GridSearchCV does exactly same thing as for loop above but in a single line of code**

In [ ]:
from sklearn.model_selection import GridSearchCV

paraMeter = {                     #adjust parameter based on your requirement
             
    'C': [1,10,20,30],
    'kernel': ['rbf','linear', 'poly']
}

In [22]:
result = GridSearchCV(SVC(gamma='auto'), paraMeter, cv=5)

In [23]:
result.fit(features, target)

result.cv_results_

{'mean_fit_time': array([0.00340071, 0.39025192, 0.00300069, 0.00280066, 2.15227666,
        0.00300002, 0.00320001, 1.60888495, 0.0032002 , 0.00339999,
        1.78583212, 0.00319986]),
 'std_fit_time': array([4.89959789e-04, 1.82832403e-01, 2.33601546e-07, 4.00042545e-04,
        1.05165300e+00, 2.61174468e-07, 4.00328647e-04, 5.04868967e-01,
        3.99994946e-04, 4.89959812e-04, 4.62216685e-01, 4.00161914e-04]),
 'mean_score_time': array([0.00220046, 0.00140028, 0.00100017, 0.00180035, 0.00180097,
        0.00120096, 0.00180101, 0.00100036, 0.00140076, 0.00200119,
        0.00180292, 0.00140119]),
 'std_score_time': array([4.00257139e-04, 4.90037648e-04, 0.00000000e+00, 4.00090228e-04,
        4.00042772e-04, 3.99804154e-04, 4.00066546e-04, 3.81469727e-07,
        4.89648366e-04, 1.90734863e-07, 4.00795205e-04, 4.89881968e-04]),
 'param_C': masked_array(data=[1, 1, 1, 10, 10, 10, 20, 20, 20, 30, 30, 30],
              mask=[False, False, False, False, False, False, False, False,
 

In [25]:
result.best_params_

{'C': 30, 'kernel': 'linear'}

In [26]:
result.best_score_

0.9209129017233348