<h1 style=color:violet>Broadcasting and Grabbing</h1>
<h1 style=color:green>Numpy Operations</h1>    

<h2 style=color:orange>Broadcasting and Grabbing</h2>

In [2]:
import numpy as np

In [3]:
array_1d = np.arange(0,10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Take a slice of the array and set it equal to some number, say 500.<br>

        array_1d[0:5] = 500 
this will **broadcast the value of 500 to the first 5 elements** of the array_1d

In [4]:
array_1d[:5] = 500 
array_1d

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [5]:
# Lets create a 2D martix with zeros
array_zeros = np.zeros((4,4)) #As usal dtype is "float"
array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# Lets create a 2D martix with ones
array_2d = np.ones((4,4),dtype='int') 
array_2d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [7]:
# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

array([[300, 300, 300, 300],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1]])

In [9]:
array_2d + np.arange(0,4)  #[0,1,2,3]

array([[300, 301, 302, 303],
       [  1,   2,   3,   4],
       [  1,   2,   3,   4],
       [  1,   2,   3,   4]])

In [10]:
array_2d[2] + np.arange(5,9) #[5,6,7,8] added in 3rd row

array([6, 7, 8, 9])

In [11]:
array_2d

array([[300, 300, 300, 300],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1]])

In [12]:
array_2d + 300

array([[600, 600, 600, 600],
       [301, 301, 301, 301],
       [301, 301, 301, 301],
       [301, 301, 301, 301]])

In [13]:
array_2d

array([[300, 300, 300, 300],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1]])

In [14]:
array_2d[[0, 2, 3]] #1st,3rd,4th rows

array([[300, 300, 300, 300],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1]])

In [15]:
array_2d[:,:1] #all rows:1st and 2nd columns

array([[300],
       [  1],
       [  1],
       [  1]])

In [16]:
array_2d[[3,0,1,1,1,1]]

array([[  1,   1,   1,   1],
       [300, 300, 300, 300],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1],
       [  1,   1,   1,   1]])

In [17]:
array_2d = np.arange(24).reshape(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
array_2d[[2,3]] #grabbing rows [2][3]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
# grabbing columns
array_2d[:,[3,2]]

array([[ 3,  2],
       [ 7,  6],
       [11, 10],
       [15, 14],
       [19, 18],
       [23, 22]])

In [20]:
array_1d = np.arange(1,11)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can apply condition such as >, <, == etc

In [21]:
array_1d > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [22]:
# lets create a bool_array for some condition, say array_1d > 3
bool_array = array_1d > 3
bool_array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

Lets create a mask to **filter out the even numbers in "array_1d"**

In [23]:
array_1d % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [24]:
0 == array_1d % 2

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [25]:
mod_2_mask_1d = array_1d % 2 != 0 
mod_2_mask_1d

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [26]:
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
array_1d[mod_2_mask_1d] #array([True, False, True, False, True, False, True, False, True, False])

array([1, 3, 5, 7, 9])

<h2 style=color:orange>Numpy Operation</h2>

* <b>Arithmetic operations</b>
* <b>Universal Functions (ufunc)</b>

### Arithmetic operations

In [28]:
# Let's create an array using arange() method
arr = np.arange(0,5)
arr  

array([0, 1, 2, 3, 4])

In [29]:
# Adding two arrays
arr + arr  #[0, 1, 2, 3, 4] + [0, 1, 2, 3, 4]

array([0, 2, 4, 6, 8])

In [30]:
# Subtracting two arrays
arr - arr

array([0, 0, 0, 0, 0])

In [31]:
# Multiplication
arr * arr

array([ 0,  1,  4,  9, 16])

In [32]:
# Division
arr / arr

C:\Users\Thuhin\AppData\Local\Temp\ipykernel_2632\931624765.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.])

In [33]:
1/arr #[0, 1, 2, 3, 4]

C:\Users\Thuhin\AppData\Local\Temp\ipykernel_2632\3632844458.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr #[0, 1, 2, 3, 4]


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [34]:
# Power of all the elements in an array
arr ** 2

array([ 0,  1,  4,  9, 16])

In [35]:
# Multiplication with scalar 
2 * arr #[0, 1, 2, 3, 4]

array([0, 2, 4, 6, 8])

### Universal functions

In [36]:
# Square root
np.sqrt(arr) #[0, 1, 2, 3, 4]

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [37]:
# max and min values
np.max(arr), np.min(arr)

(4, 0)

In [38]:
arr.max(),arr.min() # max and min values

(4, 0)

In [39]:
# Trigonometric functions, e.g. sin, cos, tan ......
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

**Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [40]:
array_2d= np.arange(6).reshape(3,2)
array_2d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [41]:
array_2d.shape

(3, 2)

**Calculate the sum of all the numbers in array_2d?**

In [42]:
array_2d.sum()

15

In [43]:
array_2d.sum(axis=0) #axis = 0 means --> column

array([6, 9])

**Calculate sum of all the rows and columns in array_2d.**

In [44]:
print("Row sum:", array_2d.sum(axis=1))
print("Columns sum:", array_2d.sum(axis=0))

Row sum: [1 5 9]
Columns sum: [6 9]


**Calculate the standard deviation of the values in array_2d.**

In [46]:
array_2d.std() # std() = standard deviation

1.707825127659933

**Create a boolean mask and list out the numbers that are not divisible by 3 in array_2d.**

In [48]:
array_2d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [49]:
array_2d % 3 == 0

array([[ True, False],
       [False,  True],
       [False, False]])

In [50]:
mask_mod_3 = 0 != array_2d % 3
mask_mod_3

array([[False,  True],
       [ True, False],
       [ True,  True]])

In [51]:
mask_mod_3 = 0 != array_2d % 3  # Creating mask for the said condition
array_2d[mask_mod_3]            # pass the boolean mask to array_2d to return the required results

array([1, 2, 4, 5])