# NumPy Essentials(Part-2)
<h2 style=color:green>Slicing 1-D and 2-D arrays</h2>

#### Indexing & slicing of 1-D arrays (vectors)
####  Indexing & slicing 2-D arrays (matrices)

<h3 style=color:red>Indexing & slicing 1-D arrays (vectors)</h3>

In [4]:
import numpy as np #import numpy

In [5]:
array_1d = np.array([-10, -2, 0, 2, 17, 106,200])

In [6]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [7]:
# Getting value at certain index
array_1d[2]

0

In [8]:
# Getting a range value
array_1d[0:3]
# array_1d is included in the out to compare and understand

array([-10,  -2,   0])

In [9]:
# Using -ve index 
array_1d[-2]

106

In [10]:
array_1d[1:-2] # 1 inclusive and -2 exclusive in this case

array([-2,  0,  2, 17])

In [11]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [12]:
# Getting up-to and from certain index -- remember index starts from '0'
array_1d[:2]

array([-10,  -2])

In [13]:
array_1d[2:]

array([  0,   2,  17, 106, 200])

In [14]:
# Assigning a new value to a certain index in the array 
array_1d[0] = -102

In [15]:
array_1d # The first element is changed to -102

array([-102,   -2,    0,    2,   17,  106,  200])

<h3 style=color:red>Indexing & slicing 2-D arrays (matrices)</h3>

In [16]:
array_2d = np.arange(24).reshape(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

To access any element, the general format is: <br>
* **`array_2d[row][col]`** <br>or<br> 
* **`array_2d[row,col]`**. 

We will use `[row,col]`, easier to use comma ',' for clarity.

In [18]:
# To get a complete row
array_2d[2]

array([ 8,  9, 10, 11])

In [19]:
array_2d[-4] # -0 and 0 is same inedex

array([ 8,  9, 10, 11])

In [20]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
row = 5
column = 2
array_2d[row, column]

22

In [22]:
#Just to make sure, using [row][col] :)
array_2d[5,2]

22

In [23]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
array_2d[:2,:2] # 2D array slicing

array([[0, 1],
       [4, 5]])