# NumPy Essentials(Part-1)

As a fundamental package for scientific computing, NumPy provides the foundations of mathematical, scientific, engineering and data science programming within the Python Echo-system. NumPy’s main object is the homogeneous multidimensional array.<br> 

**NumPY stands for? Ans: Numerical Python  
Numpy developed by? Ans: Travis Oliphant**

## Numpy Arrays
### `arange()`,  `linspace()`, `zeros()`,  `ones()`, `eye()`, `rand()`, `randn()`, `randint()`

<h2 style=color:orange>Array Methods & Attributes</h2>

Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape(), max(), min(), argmax(), argmin()

### Attributes
* `size, shape, dtype` 

In [29]:
import numpy as np  #if numpy is not install then--> {!pip install numpy} install it using this command

NumPy has many built-in functions and capabilities. We will focus on some of the most important and key concepts of this powerful library.

## Numpy Arrays
* **Vectors:** Vectors are strictly 1-dimensional array
*  **Matrices:** Matrices are 2-dimensional (matrix can still have only one row or one column).

## Creating NumPy Arrays

In [30]:
# Lets create a Python list. 
my_list = [-1,0,1]
my_list

[-1, 0, 1]

To create a NumPy array, from a Python data structure, we use NumPy's array function. <br>
The NumPy's array function can be accessed by typing "np.array". <br>
We need to cast our Python data structure, my_list, as a parameter to the array function.<br>

In [31]:
my_array = np.array(my_list)
my_array

array([-1,  0,  1])

In [32]:
# Lets create and cast a list of list to generate 2-D array 
my_matrix = [[1,2,3],[4,5,6],[7,8,9], [4, 5, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 9]]

In [33]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 9]])

In [34]:
# We can use Tuple instead of list as well. 
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

### Array creation using NumPy's Built-in methods

Most of the times, we use NumPy built-in methods to create arrays. These are much simpler and faster.

### `arange()`

* arange() is very much similar to Python function range() <br>
* Syntax: arange([start,] stop[, step,], dtype=None) <br>
* Return evenly spaced values within a given interval. <br>

*Press shift+tab for the documentation.*

In [35]:
np.arange(100) # similar to range() in Python, not including 100

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
np.arange(3,10,2) #start(3),stop(10),step(2)

array([3, 5, 7, 9])

In [37]:
# We can give the step and dtype
np.arange(0,10,2, dtype=float) #As Usal dtype is "integer" 

array([0., 2., 4., 6., 8.])

### `linspace()`
Return evenly spaced numbers over a specified interval.<br>
*Press shift+tab for the documentation.*

In [38]:
# start from 1 & end at 2 with 100 evenly spaced points b/w 1 to 2.
np.linspace(1, 2, 100, retstep = True) # strat(1),stop(2),need values no. of 100(inbetween 1-2)
#retstep use to check difference between 2 values

(array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
        1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
        1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
        1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
        1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
        1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
        1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
        1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
        1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
        1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
        1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
        1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
        1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
        1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
        1.70707071, 1.71717172, 1.72727273, 1.73

In [39]:
1.01010101-1 #check retstep

0.010101010000000077

In [40]:
my_linspace = np.linspace(9, 15, 20, retstep=True)
my_linspace

(array([ 9.        ,  9.31578947,  9.63157895,  9.94736842, 10.26315789,
        10.57894737, 10.89473684, 11.21052632, 11.52631579, 11.84210526,
        12.15789474, 12.47368421, 12.78947368, 13.10526316, 13.42105263,
        13.73684211, 14.05263158, 14.36842105, 14.68421053, 15.        ]),
 0.3157894736842105)

In [41]:
np.linspace(2,15,30,retstep=True)

(array([ 2.        ,  2.44827586,  2.89655172,  3.34482759,  3.79310345,
         4.24137931,  4.68965517,  5.13793103,  5.5862069 ,  6.03448276,
         6.48275862,  6.93103448,  7.37931034,  7.82758621,  8.27586207,
         8.72413793,  9.17241379,  9.62068966, 10.06896552, 10.51724138,
        10.96551724, 11.4137931 , 11.86206897, 12.31034483, 12.75862069,
        13.20689655, 13.65517241, 14.10344828, 14.55172414, 15.        ]),
 0.4482758620689655)

In [42]:
x = np.arange(0,16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
x.shape #shape of this array

(16,)

In [44]:
a = x.reshape(4,4) #change the array shape
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
a.shape

(4, 4)

In [46]:
a = a.reshape(1,16)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

## Random 

We can also create arrays with random numbers using Numpy's built-in functions in Random module.<br>
*np.random. and then press tab for the options with random*

### `rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [47]:
np.random.rand(5) # 1-D array with three elements

array([0.41448588, 0.70066843, 0.75522759, 0.88761194, 0.19848015])

In [48]:
np.random.rand(6,4) # row, col, note we are not passing a tuple here, each dimension as a separate argument

array([[0.17121038, 0.31013282, 0.31834413, 0.83336379],
       [0.70265541, 0.22907284, 0.90440707, 0.38572496],
       [0.95820705, 0.83218389, 0.55657408, 0.92663359],
       [0.87722489, 0.45817635, 0.19016447, 0.49682446],
       [0.52130339, 0.86272213, 0.40779569, 0.48944158],
       [0.11865071, 0.484031  , 0.36477906, 0.31305175]])

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.<br>
*Press shift+tab for the documentation.*

In [49]:
np.random.randn(10, 5)

array([[ 0.95095266,  0.23371032,  1.71953369, -2.01827393,  0.16714505],
       [ 1.40065812,  0.88982944, -1.02640381, -0.71349961,  1.86373375],
       [-0.4411609 ,  0.53488464,  1.38428876, -1.55132433,  0.42121987],
       [ 1.0224534 , -1.13078996, -0.25110293, -0.2552345 ,  0.23925778],
       [-0.51735347,  1.18860972,  0.84630202, -0.5841929 , -0.69145668],
       [-0.88587037, -0.87300038, -0.83041588,  0.06315366, -0.23726595],
       [-0.56444076,  0.68663579, -0.67946262,  0.58527112,  0.12209801],
       [-1.49978739, -0.7809377 , -0.83067118, -0.25254   , -1.68111487],
       [ 1.24749462, -1.37629071,  0.51473054, -0.50649457, -0.34683936],
       [-1.19983391,  0.26532028,  0.61244387, -0.54489807, -0.34102984]])

In [50]:
normal_array = np.random.randn(10,1) # no tuple, each dimension as a separate argument
normal_array

array([[-0.34492332],
       [ 0.26578493],
       [-1.26544475],
       [-1.60957001],
       [-0.57847462],
       [-0.45083294],
       [-2.09517341],
       [-0.61035987],
       [-1.21289011],
       [ 1.06882725]])

### `randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [51]:
np.random.randint(10,20) #returns one random int, 10 inclusive, 20 exclusive

13

In [52]:
x = np.random.randint(100,500,20)
x

array([267, 316, 351, 138, 214, 459, 486, 391, 492, 467, 259, 385, 150,
       182, 171, 427, 430, 374, 298, 228])

In [53]:
x.reshape(4,5) #change the array shape

array([[267, 316, 351, 138, 214],
       [459, 486, 391, 492, 467],
       [259, 385, 150, 182, 171],
       [427, 430, 374, 298, 228]])

In [54]:
np.random.randint(100,500,20).reshape(4,5) #create an array and change the shape 

array([[126, 243, 212, 376, 429],
       [184, 330, 412, 368, 118],
       [426, 492, 256, 187, 162],
       [362, 488, 172, 310, 466]])

<h1 style=color:orange>Methods & Attributes</h1>

### Methods
* `max(), min(), argmax(), argmin()` 

In [55]:
# lets create 2 arrays using arange() and randint()
array_arange = np.arange(16)
array_ranint = np.random.randint(0,100,10)

In [56]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
array_ranint

array([ 8, 58, 13, 58, 20, 40, 96, 83, 57, 25])

#### `max()` & `min()`
Useful methods for finding max or min values.

In [58]:
array_ranint.min()

8

In [59]:
array_ranint.max()

96

In [60]:
array_ranint.min(), array_ranint.max()

(8, 96)

#### `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [61]:
array_ranint.argmax() # index starts from 0

6

In [62]:
array_ranint.argmin()

0

In [63]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Attributes
* `size, shape, dtype` 

In [64]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
# Lets take vector array, array_arange 
array_arange.shape
#reshape_test.shape

(16,)

In [66]:
# Size of the array 
array_arange.size

16

In [67]:
# Type of the data.
array_arange.dtype

dtype('int32')

In [68]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [70]:
array_arange.shape = (2,8) #change and fixed the array shape

In [71]:
array_arange

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [72]:
array_arange.reshape(16,1).shape

(16, 1)

In [73]:
array_arange

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

### `zeros()`

In [74]:
array_zeros = np.zeros((4,5))
array_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### `ones()`

In [75]:
array_zeros = np.ones((4,3),dtype='int')
array_zeros

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### `eye()`

In [76]:
array_eye = np.eye(2, dtype=int)
array_eye

array([[1, 0],
       [0, 1]])